= Zeiterfassung für Gruppe XX

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Dev1 |Dev2 |Dev3 |Dev4 |Dev5 |Dev6 |Meeting
|1  |…   |…    |…    |…    |…    |…    |…    
|2  |…   |…    |…    |…    |…    |…    |…    
|3  |…   |…    |…    |…    |…    |…    |…    
|4  |…   |…    |…    |…    |…    |…    |…    
|5  |…   |…    |…    |…    |…    |…    |…    
|6  |…   |…    |…    |…    |…    |…    |…    
|7  |…   |…    |…    |…    |…    |…    |…    
|8  |…   |…    |…    |…    |…    |…    |…    
|9  |…   |…    |…    |…    |…    |…    |…    
|10  |…   |…    |…    |…    |…    |…    |…    
|11  |…   |…    |…    |…    |…    |…    |…    
|12  |…   |…    |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
