= Kickstart

The kickstart module is a template project to bootstrap the Java project in the Software Engineering lab.
The project is supposed to be copied into the group's repository to get it started easily.
It contains the following features:

* a skeleton Java 11 web application based on Spring Boot and Salespoint framework (see `src/main/java`)
* a placeholder Asciidoc file in `src/main/asciidoc` for documentation

== Important documents in this repo

* link:src/main/asciidoc/protocols[Meeting Protocols]
* link:src/main/asciidoc/time_recording.adoc[Time recording (Zeiterfassung)]
* link:src/main/asciidoc/pflichtenheft.adoc[Requirements specification (Pflichtenheft)]
* link:src/main/asciidoc/developer_documentation.adoc[Developer documentation (Entwicklerdokumentation)]

== How to run the application?

* In the IDE: find `Application.java`, right-click project, select "Run As > Java Application"
* From the command line: run `./mvnw spring-boot:run`

== How to package the application?

* Run `./mvnw clean package`. The packaged application (a JAR in `target/`) can be run with `java -jar $jarName`.
